[project]
name = "hjorthagshojdenlogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gspread==5.12.4",
    "oauth2client==4.1.3",
]
